### ISSUE TITLE
Meta Extraction Failure

### ISSUE THREAD

**Issue by AlucardNosferatu** [smoothnlp/SmoothNLP#53]
```
"C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe" "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.1\plugins\python-ce\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 54150 --file C:/Users/16413/Documents/GitHub/LostXmas/seq2seq/data/augmentation/rationalities.py
pydev debugger: process 86948 is connecting
Connected to pydev debugger (build 201.7846.77)
WARNING:SmoothNLP:HTTPConnectionPool(host='api.smoothnlp.com', port=80): Max retries exceeded with url: /nlp/query?text=%E6%AC%A2%E8%BF%8E%E4%BD%BF%E7%94%A8smoothnlp%E7%9A%84Python%E6%8E%A5%E5%8F%A3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B6BC5E1948>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/16413/Documents/GitHub/LostXmas/seq2seq/data/augmentation/rationalities.py", line 3, in <module>
    result = smoothnlp.postag('欢迎使用smoothnlp的Python接口')
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\smoothnlp\__init__.py", line 25, in postag
    return nlp.postag(text)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\smoothnlp\server\__init__.py", line 183, in postag
    tokens = extract_meta(result, "tokens")
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\smoothnlp\server\__init__.py", line 91, in extract_meta
    raise ValueError("Meta Extraction Failure")
ValueError: Meta Extraction Failure

```
code:
```
import smoothnlp

result = smoothnlp.postag('欢迎使用smoothnlp的Python接口')

print(result)
```

**Comment by zhangruinan** [comment]
can you try `ping api.smoothnlp.com` from your terminal to make sure our service is available through your network

**Comment by AlucardNosferatu** [comment]
It is ok now, thx

> can you try `ping api.smoothnlp.com` from your terminal to make sure our service is available through your network
